GET http://localhost:7071/api/HelloWorldTrigger HTTP/1.1

###
POST http://localhost:7071/api/HelloWorldTrigger HTTP/1.1

###
GET http://localhost:7071/api/calculator/4/5 HTTP/1.1

###
POST http://localhost:7071/api/calculator HTTP/1.1
Content-Type: application/json

{
    "A": 5,
    "B": 10,
    "Operation": "add"
}